// Mapeamento completo de bandeiras por país
// Cobre todas as nações FIFA + outros territórios relevantes
// Valor: emoji de bandeira (Unicode Regional Indicator Symbols)

export const COUNTRY_FLAGS = [
  { label: "🇦🇫 Afeganistão", flag: "🇦🇫" },
  { label: "🇦🇱 Albânia", flag: "🇦🇱" },
  { label: "🇩🇿 Argélia", flag: "🇩🇿" },
  { label: "🇦🇩 Andorra", flag: "🇦🇩" },
  { label: "🇦🇴 Angola", flag: "🇦🇴" },
  { label: "🇦🇬 Antígua e Barbuda", flag: "🇦🇬" },
  { label: "🇸🇦 Arábia Saudita", flag: "🇸🇦" },
  { label: "🇦🇷 Argentina", flag: "🇦🇷" },
  { label: "🇦🇲 Arménia", flag: "🇦🇲" },
  { label: "🇦🇺 Austrália", flag: "🇦🇺" },
  { label: "🇦🇹 Áustria", flag: "🇦🇹" },
  { label: "🇦🇿 Azerbaijão", flag: "🇦🇿" },
  { label: "🇧🇸 Bahamas", flag: "🇧🇸" },
  { label: "🇧🇭 Bahrein", flag: "🇧🇭" },
  { label: "🇧🇩 Bangladesh", flag: "🇧🇩" },
  { label: "🇧🇧 Barbados", flag: "🇧🇧" },
  { label: "🇧🇾 Bielorrússia", flag: "🇧🇾" },
  { label: "🇧🇪 Bélgica", flag: "🇧🇪" },
  { label: "🇧🇿 Belize", flag: "🇧🇿" },
  { label: "🇧🇯 Benim", flag: "🇧🇯" },
  { label: "🇧🇴 Bolívia", flag: "🇧🇴" },
  { label: "🇧🇦 Bósnia e Herzegovina", flag: "🇧🇦" },
  { label: "🇧🇼 Botsuana", flag: "🇧🇼" },
  { label: "🇧🇷 Brasil", flag: "🇧🇷" },
  { label: "🇧🇳 Brunei", flag: "🇧🇳" },
  { label: "🇧🇬 Bulgária", flag: "🇧🇬" },
  { label: "🇧🇫 Burkina Faso", flag: "🇧🇫" },
  { label: "🇧🇮 Burundi", flag: "🇧🇮" },
  { label: "🇧🇹 Butão", flag: "🇧🇹" },
  { label: "🇨🇻 Cabo Verde", flag: "🇨🇻" },
  { label: "🇨🇲 Camarões", flag: "🇨🇲" },
  { label: "🇰🇭 Camboja", flag: "🇰🇭" },
  { label: "🇨🇦 Canadá", flag: "🇨🇦" },
  { label: "🇶🇦 Catar", flag: "🇶🇦" },
  { label: "🇰🇿 Cazaquistão", flag: "🇰🇿" },
  { label: "🇹🇩 Chade", flag: "🇹🇩" },
  { label: "🇨🇱 Chile", flag: "🇨🇱" },
  { label: "🇨🇳 China", flag: "🇨🇳" },
  { label: "🇨🇾 Chipre", flag: "🇨🇾" },
  { label: "🇨🇴 Colômbia", flag: "🇨🇴" },
  { label: "🇰🇲 Comores", flag: "🇰🇲" },
  { label: "🇨🇬 Congo", flag: "🇨🇬" },
  { label: "🇨🇩 Congo (RDC)", flag: "🇨🇩" },
  { label: "🇰🇵 Coreia do Norte", flag: "🇰🇵" },
  { label: "🇰🇷 Coreia do Sul", flag: "🇰🇷" },
  { label: "🇨🇮 Costa do Marfim", flag: "🇨🇮" },
  { label: "🇨🇷 Costa Rica", flag: "🇨🇷" },
  { label: "🇭🇷 Croácia", flag: "🇭🇷" },
  { label: "🇨🇺 Cuba", flag: "🇨🇺" },
  { label: "🇩🇰 Dinamarca", flag: "🇩🇰" },
  { label: "🇩🇯 Jibuti", flag: "🇩🇯" },
  { label: "🇩🇲 Dominica", flag: "🇩🇲" },
  { label: "🇪🇬 Egito", flag: "🇪🇬" },
  { label: "🇸🇻 El Salvador", flag: "🇸🇻" },
  { label: "🇦🇪 Emirados Árabes Unidos", flag: "🇦🇪" },
  { label: "🇪🇨 Equador", flag: "🇪🇨" },
  { label: "🇪🇷 Eritreia", flag: "🇪🇷" },
  { label: "🇸🇰 Eslováquia", flag: "🇸🇰" },
  { label: "🇸🇮 Eslovénia", flag: "🇸🇮" },
  { label: "🇪🇸 Espanha", flag: "🇪🇸" },
  { label: "🇪🇹 Etiópia", flag: "🇪🇹" },
  { label: "🇫🇯 Fiji", flag: "🇫🇯" },
  { label: "🇵🇭 Filipinas", flag: "🇵🇭" },
  { label: "🇫🇮 Finlândia", flag: "🇫🇮" },
  { label: "🇫🇷 França", flag: "🇫🇷" },
  { label: "🇬🇦 Gabão", flag: "🇬🇦" },
  { label: "🇬🇲 Gâmbia", flag: "🇬🇲" },
  { label: "🇬🇭 Gana", flag: "🇬🇭" },
  { label: "🇬🇪 Geórgia", flag: "🇬🇪" },
  { label: "🇬🇳 Guiné", flag: "🇬🇳" },
  { label: "🇬🇼 Guiné-Bissau", flag: "🇬🇼" },
  { label: "🇬🇶 Guiné Equatorial", flag: "🇬🇶" },
  { label: "🇬🇷 Grécia", flag: "🇬🇷" },
  { label: "🇬🇩 Granada", flag: "🇬🇩" },
  { label: "🇬🇹 Guatemala", flag: "🇬🇹" },
  { label: "🇬🇾 Guiana", flag: "🇬🇾" },
  { label: "🇭🇹 Haiti", flag: "🇭🇹" },
  { label: "🇭🇳 Honduras", flag: "🇭🇳" },
  { label: "🇭🇺 Hungria", flag: "🇭🇺" },
  { label: "🇾🇪 Iémen", flag: "🇾🇪" },
  { label: "🇮🇳 Índia", flag: "🇮🇳" },
  { label: "🇮🇩 Indonésia", flag: "🇮🇩" },
  { label: "🇮🇶 Iraque", flag: "🇮🇶" },
  { label: "🇮🇷 Irão", flag: "🇮🇷" },
  { label: "🇮🇪 Irlanda", flag: "🇮🇪" },
  { label: "🇮🇸 Islândia", flag: "🇮🇸" },
  { label: "🇮🇱 Israel", flag: "🇮🇱" },
  { label: "🇮🇹 Itália", flag: "🇮🇹" },
  { label: "🇯🇲 Jamaica", flag: "🇯🇲" },
  { label: "🇯🇵 Japão", flag: "🇯🇵" },
  { label: "🇯🇴 Jordânia", flag: "🇯🇴" },
  { label: "🇰🇼 Kuwait", flag: "🇰🇼" },
  { label: "🇱🇦 Laos", flag: "🇱🇦" },
  { label: "🇱🇸 Lesoto", flag: "🇱🇸" },
  { label: "🇱🇻 Letónia", flag: "🇱🇻" },
  { label: "🇱🇧 Líbano", flag: "🇱🇧" },
  { label: "🇱🇷 Libéria", flag: "🇱🇷" },
  { label: "🇱🇾 Líbia", flag: "🇱🇾" },
  { label: "🇱🇮 Liechtenstein", flag: "🇱🇮" },
  { label: "🇱🇹 Lituânia", flag: "🇱🇹" },
  { label: "🇱🇺 Luxemburgo", flag: "🇱🇺" },
  { label: "🇲🇰 Macedónia do Norte", flag: "🇲🇰" },
  { label: "🇲🇬 Madagáscar", flag: "🇲🇬" },
  { label: "🇲🇼 Malawi", flag: "🇲🇼" },
  { label: "🇲🇾 Malásia", flag: "🇲🇾" },
  { label: "🇲🇻 Maldivas", flag: "🇲🇻" },
  { label: "🇲🇱 Mali", flag: "🇲🇱" },
  { label: "🇲🇹 Malta", flag: "🇲🇹" },
  { label: "🇲🇦 Marrocos", flag: "🇲🇦" },
  { label: "🇲🇷 Mauritânia", flag: "🇲🇷" },
  { label: "🇲🇺 Maurícias", flag: "🇲🇺" },
  { label: "🇲🇽 México", flag: "🇲🇽" },
  { label: "🇲🇲 Mianmar", flag: "🇲🇲" },
  { label: "🇫🇲 Micronésia", flag: "🇫🇲" },
  { label: "🇲🇿 Moçambique", flag: "🇲🇿" },
  { label: "🇲🇩 Moldávia", flag: "🇲🇩" },
  { label: "🇲🇨 Mónaco", flag: "🇲🇨" },
  { label: "🇲🇳 Mongólia", flag: "🇲🇳" },
  { label: "🇲🇪 Montenegro", flag: "🇲🇪" },
  { label: "🇳🇦 Namíbia", flag: "🇳🇦" },
  { label: "🇳🇷 Nauru", flag: "🇳🇷" },
  { label: "🇳🇵 Nepal", flag: "🇳🇵" },
  { label: "🇳🇮 Nicarágua", flag: "🇳🇮" },
  { label: "🇳🇪 Níger", flag: "🇳🇪" },
  { label: "🇳🇬 Nigéria", flag: "🇳🇬" },
  { label: "🇳🇴 Noruega", flag: "🇳🇴" },
  { label: "🇳🇿 Nova Zelândia", flag: "🇳🇿" },
  { label: "🇴🇲 Omã", flag: "🇴🇲" },
  { label: "🇳🇱 Países Baixos", flag: "🇳🇱" },
  { label: "🇵🇼 Palau", flag: "🇵🇼" },
  { label: "🇵🇸 Palestina", flag: "🇵🇸" },
  { label: "🇵🇦 Panamá", flag: "🇵🇦" },
  { label: "🇵🇬 Papua-Nova Guiné", flag: "🇵🇬" },
  { label: "🇵🇰 Paquistão", flag: "🇵🇰" },
  { label: "🇵🇾 Paraguai", flag: "🇵🇾" },
  { label: "🇵🇪 Peru", flag: "🇵🇪" },
  { label: "🇵🇱 Polónia", flag: "🇵🇱" },
  { label: "🇵🇹 Portugal", flag: "🇵🇹" },
  { label: "🇰🇪 Quénia", flag: "🇰🇪" },
  { label: "🇰🇬 Quirguistão", flag: "🇰🇬" },
  { label: "🇰🇮 Quiribáti", flag: "🇰🇮" },
  { label: "🇬🇧 Reino Unido", flag: "🇬🇧" },
  { label: "🏴󠁧󠁢󠁥󠁮󠁧󠁿 Inglaterra", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { label: "🏴󠁧󠁢󠁳󠁣󠁴󠁿 Escócia", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { label: "🏴󠁧󠁢󠁷󠁬󠁳󠁿 País de Gales", flag: "🏴󠁧󠁢󠁷󠁬󠁳󠁿" },
  { label: "🇨🇫 República Centro-Africana", flag: "🇨🇫" },
  { label: "🇨🇿 República Checa", flag: "🇨🇿" },
  { label: "🇩🇴 República Dominicana", flag: "🇩🇴" },
  { label: "🇷🇴 Roménia", flag: "🇷🇴" },
  { label: "🇷🇼 Ruanda", flag: "🇷🇼" },
  { label: "🇷🇺 Rússia", flag: "🇷🇺" },
  { label: "🇼🇸 Samoa", flag: "🇼🇸" },
  { label: "🇸🇲 São Marinho", flag: "🇸🇲" },
  { label: "🇸🇹 São Tomé e Príncipe", flag: "🇸🇹" },
  { label: "🇰🇳 São Cristóvão e Nevis", flag: "🇰🇳" },
  { label: "🇱🇨 Santa Lúcia", flag: "🇱🇨" },
  { label: "🇻🇨 São Vicente e Granadinas", flag: "🇻🇨" },
  { label: "🇸🇳 Senegal", flag: "🇸🇳" },
  { label: "🇸🇱 Serra Leoa", flag: "🇸🇱" },
  { label: "🇷🇸 Sérvia", flag: "🇷🇸" },
  { label: "🇸🇨 Seychelles", flag: "🇸🇨" },
  { label: "🇸🇬 Singapura", flag: "🇸🇬" },
  { label: "🇸🇾 Síria", flag: "🇸🇾" },
  { label: "🇸🇴 Somália", flag: "🇸🇴" },
  { label: "🇱🇰 Sri Lanka", flag: "🇱🇰" },
  { label: "🇸🇿 Suazilândia", flag: "🇸🇿" },
  { label: "🇸🇩 Sudão", flag: "🇸🇩" },
  { label: "🇸🇸 Sudão do Sul", flag: "🇸🇸" },
  { label: "🇸🇪 Suécia", flag: "🇸🇪" },
  { label: "🇨🇭 Suíça", flag: "🇨🇭" },
  { label: "🇸🇷 Suriname", flag: "🇸🇷" },
  { label: "🇹🇯 Tajiquistão", flag: "🇹🇯" },
  { label: "🇹🇭 Tailândia", flag: "🇹🇭" },
  { label: "🇹🇼 Taiwan", flag: "🇹🇼" },
  { label: "🇹🇿 Tanzânia", flag: "🇹🇿" },
  { label: "🇹🇱 Timor-Leste", flag: "🇹🇱" },
  { label: "🇹🇬 Togo", flag: "🇹🇬" },
  { label: "🇹🇴 Tonga", flag: "🇹🇴" },
  { label: "🇹🇹 Trindade e Tobago", flag: "🇹🇹" },
  { label: "🇹🇳 Tunísia", flag: "🇹🇳" },
  { label: "🇹🇲 Turquemenistão", flag: "🇹🇲" },
  { label: "🇹🇷 Turquia", flag: "🇹🇷" },
  { label: "🇹🇻 Tuvalu", flag: "🇹🇻" },
  { label: "🇺🇦 Ucrânia", flag: "🇺🇦" },
  { label: "🇺🇬 Uganda", flag: "🇺🇬" },
  { label: "🇺🇾 Uruguai", flag: "🇺🇾" },
  { label: "🇺🇿 Uzbequistão", flag: "🇺🇿" },
  { label: "🇻🇺 Vanuatu", flag: "🇻🇺" },
  { label: "🇻🇦 Vaticano", flag: "🇻🇦" },
  { label: "🇻🇪 Venezuela", flag: "🇻🇪" },
  { label: "🇻🇳 Vietname", flag: "🇻🇳" },
  { label: "🇿🇲 Zâmbia", flag: "🇿🇲" },
  { label: "🇿🇼 Zimbabué", flag: "🇿🇼" },
];

// Lookup rápido por emoji
export const FLAG_SET = new Set(COUNTRY_FLAGS.map((c) => c.flag));
