version: '3.8'
services:
  backend:
    build: ./server
    volumes:
      - ./server/db:/app/db

  frontend:
    build: ./client
    environment:
      - VITE_BACKEND_URL=http://localhost:3000
    networks:
      cftunnel:
        ipv4_address: 172.100.0.57

networks:
  cftunnel:
    external: true
